sourcegraph/deploy-sourcegraph-docker-customer-replica-1

pure-docker/deploy-blobstore.sh
pure-docker/deploy-cadvisor.sh
pure-docker/deploy-codeinsights-db.sh
pure-docker/deploy-codeintel-db.sh
pure-docker/deploy-frontend-internal.sh
pure-docker/deploy-frontend.sh
pure-docker/deploy-github-proxy.sh
pure-docker/deploy-gitserver.sh
pure-docker/deploy-grafana.sh
pure-docker/deploy-migrator.sh
pure-docker/deploy-node-exporter.sh
pure-docker/deploy-otel-collector.sh
pure-docker/deploy-pgsql.sh
pure-docker/deploy-precise-code-intel-worker.sh
pure-docker/deploy-prometheus.sh
pure-docker/deploy-redis-cache.sh
pure-docker/deploy-redis-store.sh
pure-docker/deploy-repo-updater.sh
pure-docker/deploy-searcher.sh
pure-docker/deploy-symbols.sh
pure-docker/deploy-syntect-server.sh
pure-docker/deploy-worker.sh
pure-docker/deploy-zoekt-indexserver.sh
pure-docker/deploy-zoekt-webserver.sh

This pull request is part of the Sourcegraph 4.4.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.4.0)

release: sourcegraph@4.4.0

---

pure-docker/deploy-blobstore.sh
pure-docker/deploy-cadvisor.sh
pure-docker/deploy-codeinsights-db.sh
pure-docker/deploy-codeintel-db.sh
pure-docker/deploy-frontend-internal.sh
pure-docker/deploy-frontend.sh
pure-docker/deploy-github-proxy.sh
pure-docker/deploy-gitserver.sh
pure-docker/deploy-grafana.sh
pure-docker/deploy-migrator.sh
pure-docker/deploy-node-exporter.sh
pure-docker/deploy-otel-collector.sh
pure-docker/deploy-pgsql.sh
pure-docker/deploy-precise-code-intel-worker.sh
pure-docker/deploy-prometheus.sh
pure-docker/deploy-redis-cache.sh
pure-docker/deploy-redis-store.sh
pure-docker/deploy-repo-updater.sh
pure-docker/deploy-searcher.sh
pure-docker/deploy-symbols.sh
pure-docker/deploy-syntect-server.sh
pure-docker/deploy-worker.sh
pure-docker/deploy-zoekt-indexserver.sh
pure-docker/deploy-zoekt-webserver.sh

This pull request is part of the Sourcegraph 4.4.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.4.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/46931)

release: sourcegraph@4.4.1

---

pure-docker/deploy-blobstore.sh
pure-docker/deploy-cadvisor.sh
pure-docker/deploy-codeinsights-db.sh
pure-docker/deploy-codeintel-db.sh
pure-docker/deploy-frontend-internal.sh
pure-docker/deploy-frontend.sh
pure-docker/deploy-github-proxy.sh
pure-docker/deploy-gitserver.sh
pure-docker/deploy-grafana.sh
pure-docker/deploy-migrator.sh
pure-docker/deploy-node-exporter.sh
pure-docker/deploy-otel-collector.sh
pure-docker/deploy-pgsql.sh
pure-docker/deploy-precise-code-intel-worker.sh
pure-docker/deploy-prometheus.sh
pure-docker/deploy-redis-cache.sh
pure-docker/deploy-redis-store.sh
pure-docker/deploy-repo-updater.sh
pure-docker/deploy-searcher.sh
pure-docker/deploy-symbols.sh
pure-docker/deploy-syntect-server.sh
pure-docker/deploy-worker.sh
pure-docker/deploy-zoekt-indexserver.sh
pure-docker/deploy-zoekt-webserver.sh

This pull request is part of the Sourcegraph 4.4.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.4.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/47256)

release: sourcegraph@4.4.2

---

pure-docker/deploy-blobstore.sh
pure-docker/deploy-cadvisor.sh
pure-docker/deploy-codeinsights-db.sh
pure-docker/deploy-codeintel-db.sh
pure-docker/deploy-frontend-internal.sh
pure-docker/deploy-frontend.sh
pure-docker/deploy-github-proxy.sh
pure-docker/deploy-gitserver.sh
pure-docker/deploy-grafana.sh
pure-docker/deploy-migrator.sh
pure-docker/deploy-node-exporter.sh
pure-docker/deploy-otel-collector.sh
pure-docker/deploy-pgsql.sh
pure-docker/deploy-precise-code-intel-worker.sh
pure-docker/deploy-prometheus.sh
pure-docker/deploy-redis-cache.sh
pure-docker/deploy-redis-store.sh
pure-docker/deploy-repo-updater.sh
pure-docker/deploy-searcher.sh
pure-docker/deploy-symbols.sh
pure-docker/deploy-syntect-server.sh
pure-docker/deploy-worker.sh
pure-docker/deploy-zoekt-indexserver.sh
pure-docker/deploy-zoekt-webserver.sh

This pull request is part of the Sourcegraph 4.5.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.5.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/47836)

release: sourcegraph@4.5.0

---

pure-docker/deploy-blobstore.sh
pure-docker/deploy-cadvisor.sh
pure-docker/deploy-codeinsights-db.sh
pure-docker/deploy-codeintel-db.sh
pure-docker/deploy-frontend-internal.sh
pure-docker/deploy-frontend.sh
pure-docker/deploy-github-proxy.sh
pure-docker/deploy-gitserver.sh
pure-docker/deploy-grafana.sh
pure-docker/deploy-migrator.sh
pure-docker/deploy-node-exporter.sh
pure-docker/deploy-otel-collector.sh
pure-docker/deploy-pgsql.sh
pure-docker/deploy-precise-code-intel-worker.sh
pure-docker/deploy-prometheus.sh
pure-docker/deploy-redis-cache.sh
pure-docker/deploy-redis-store.sh
pure-docker/deploy-repo-updater.sh
pure-docker/deploy-searcher.sh
pure-docker/deploy-symbols.sh
pure-docker/deploy-syntect-server.sh
pure-docker/deploy-worker.sh
pure-docker/deploy-zoekt-indexserver.sh
pure-docker/deploy-zoekt-webserver.sh

This pull request is part of the Sourcegraph 4.5.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.5.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/48151)

release: sourcegraph@4.5.1

---

pure-docker/deploy-blobstore.sh
pure-docker/deploy-cadvisor.sh
pure-docker/deploy-codeinsights-db.sh
pure-docker/deploy-codeintel-db.sh
pure-docker/deploy-frontend-internal.sh
pure-docker/deploy-frontend.sh
pure-docker/deploy-github-proxy.sh
pure-docker/deploy-gitserver.sh
pure-docker/deploy-grafana.sh
pure-docker/deploy-migrator.sh
pure-docker/deploy-node-exporter.sh
pure-docker/deploy-otel-collector.sh
pure-docker/deploy-pgsql.sh
pure-docker/deploy-precise-code-intel-worker.sh
pure-docker/deploy-prometheus.sh
pure-docker/deploy-redis-cache.sh
pure-docker/deploy-redis-store.sh
pure-docker/deploy-repo-updater.sh
pure-docker/deploy-searcher.sh
pure-docker/deploy-symbols.sh
pure-docker/deploy-syntect-server.sh
pure-docker/deploy-worker.sh
pure-docker/deploy-zoekt-indexserver.sh
pure-docker/deploy-zoekt-webserver.sh

This pull request is part of the Sourcegraph 5.0.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/50405)

release: sourcegraph@5.0.1

---

pure-docker/deploy-blobstore.sh
pure-docker/deploy-cadvisor.sh
pure-docker/deploy-codeinsights-db.sh
pure-docker/deploy-codeintel-db.sh
pure-docker/deploy-frontend-internal.sh
pure-docker/deploy-frontend.sh
pure-docker/deploy-github-proxy.sh
pure-docker/deploy-gitserver.sh
pure-docker/deploy-grafana.sh
pure-docker/deploy-migrator.sh
pure-docker/deploy-node-exporter.sh
pure-docker/deploy-otel-collector.sh
pure-docker/deploy-pgsql.sh
pure-docker/deploy-precise-code-intel-worker.sh
pure-docker/deploy-prometheus.sh
pure-docker/deploy-redis-cache.sh
pure-docker/deploy-redis-store.sh
pure-docker/deploy-repo-updater.sh
pure-docker/deploy-searcher.sh
pure-docker/deploy-symbols.sh
pure-docker/deploy-syntect-server.sh
pure-docker/deploy-worker.sh
pure-docker/deploy-zoekt-indexserver.sh
pure-docker/deploy-zoekt-webserver.sh

This pull request is part of the Sourcegraph 5.0.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/50811)

release: sourcegraph@5.0.2

---

pure-docker/deploy-blobstore.sh
pure-docker/deploy-cadvisor.sh
pure-docker/deploy-codeinsights-db.sh
pure-docker/deploy-codeintel-db.sh
pure-docker/deploy-frontend-internal.sh
pure-docker/deploy-frontend.sh
pure-docker/deploy-github-proxy.sh
pure-docker/deploy-gitserver.sh
pure-docker/deploy-grafana.sh
pure-docker/deploy-migrator.sh
pure-docker/deploy-node-exporter.sh
pure-docker/deploy-otel-collector.sh
pure-docker/deploy-pgsql.sh
pure-docker/deploy-precise-code-intel-worker.sh
pure-docker/deploy-prometheus.sh
pure-docker/deploy-redis-cache.sh
pure-docker/deploy-redis-store.sh
pure-docker/deploy-repo-updater.sh
pure-docker/deploy-searcher.sh
pure-docker/deploy-symbols.sh
pure-docker/deploy-syntect-server.sh
pure-docker/deploy-worker.sh
pure-docker/deploy-zoekt-indexserver.sh
pure-docker/deploy-zoekt-webserver.sh

This pull request is part of the Sourcegraph 5.0.3 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/51302)

release: sourcegraph@5.0.3

---

pure-docker/deploy-blobstore.sh
pure-docker/deploy-cadvisor.sh
pure-docker/deploy-codeinsights-db.sh
pure-docker/deploy-codeintel-db.sh
pure-docker/deploy-embeddings.sh
pure-docker/deploy-frontend-internal.sh
pure-docker/deploy-frontend.sh
pure-docker/deploy-github-proxy.sh
pure-docker/deploy-gitserver.sh
pure-docker/deploy-grafana.sh
pure-docker/deploy-migrator.sh
pure-docker/deploy-node-exporter.sh
pure-docker/deploy-otel-collector.sh
pure-docker/deploy-pgsql.sh
pure-docker/deploy-precise-code-intel-worker.sh
pure-docker/deploy-prometheus.sh
pure-docker/deploy-redis-cache.sh
pure-docker/deploy-redis-store.sh
pure-docker/deploy-repo-updater.sh
pure-docker/deploy-searcher.sh
pure-docker/deploy-symbols.sh
pure-docker/deploy-syntect-server.sh
pure-docker/deploy-worker.sh
pure-docker/deploy-zoekt-indexserver.sh
pure-docker/deploy-zoekt-webserver.sh
pure-docker/deploy.sh
pure-docker/teardown.sh
test/smoke-test.sh

This pull request is part of the Sourcegraph 5.0.4 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.4)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/52092)

release: sourcegraph@5.0.4

---

pure-docker/deploy-blobstore.sh
pure-docker/deploy-cadvisor.sh
pure-docker/deploy-codeinsights-db.sh
pure-docker/deploy-codeintel-db.sh
pure-docker/deploy-embeddings.sh
pure-docker/deploy-frontend-internal.sh
pure-docker/deploy-frontend.sh
pure-docker/deploy-github-proxy.sh
pure-docker/deploy-gitserver.sh
pure-docker/deploy-grafana.sh
pure-docker/deploy-migrator.sh
pure-docker/deploy-node-exporter.sh
pure-docker/deploy-otel-collector.sh
pure-docker/deploy-pgsql.sh
pure-docker/deploy-precise-code-intel-worker.sh
pure-docker/deploy-prometheus.sh
pure-docker/deploy-redis-cache.sh
pure-docker/deploy-redis-store.sh
pure-docker/deploy-repo-updater.sh
pure-docker/deploy-searcher.sh
pure-docker/deploy-symbols.sh
pure-docker/deploy-syntect-server.sh
pure-docker/deploy-worker.sh
pure-docker/deploy-zoekt-indexserver.sh
pure-docker/deploy-zoekt-webserver.sh

This pull request is part of the Sourcegraph 5.0.5 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.5)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/52745)

release: sourcegraph@5.0.5

---

pure-docker/deploy-blobstore.sh
pure-docker/deploy-cadvisor.sh
pure-docker/deploy-codeinsights-db.sh
pure-docker/deploy-codeintel-db.sh
pure-docker/deploy-embeddings.sh
pure-docker/deploy-frontend-internal.sh
pure-docker/deploy-frontend.sh
pure-docker/deploy-github-proxy.sh
pure-docker/deploy-gitserver.sh
pure-docker/deploy-grafana.sh
pure-docker/deploy-migrator.sh
pure-docker/deploy-node-exporter.sh
pure-docker/deploy-otel-collector.sh
pure-docker/deploy-pgsql.sh
pure-docker/deploy-precise-code-intel-worker.sh
pure-docker/deploy-prometheus.sh
pure-docker/deploy-redis-cache.sh
pure-docker/deploy-redis-store.sh
pure-docker/deploy-repo-updater.sh
pure-docker/deploy-searcher.sh
pure-docker/deploy-symbols.sh
pure-docker/deploy-syntect-server.sh
pure-docker/deploy-worker.sh
pure-docker/deploy-zoekt-indexserver.sh
pure-docker/deploy-zoekt-webserver.sh

This pull request is part of the Sourcegraph 5.0.6 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.6)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/53491)

release: sourcegraph@5.0.6

---

.tool-versions

This repo fell behind docker, updating golang.
N/A

update golang to 1.19.8 to match docker repo

---

pure-docker/deploy-blobstore.sh
pure-docker/deploy-cadvisor.sh
pure-docker/deploy-codeinsights-db.sh
pure-docker/deploy-codeintel-db.sh
pure-docker/deploy-frontend-internal.sh
pure-docker/deploy-frontend.sh
pure-docker/deploy-github-proxy.sh
pure-docker/deploy-gitserver.sh
pure-docker/deploy-grafana.sh
pure-docker/deploy-migrator.sh
pure-docker/deploy-node-exporter.sh
pure-docker/deploy-otel-collector.sh
pure-docker/deploy-pgsql.sh
pure-docker/deploy-precise-code-intel-worker.sh
pure-docker/deploy-prometheus.sh
pure-docker/deploy-redis-cache.sh
pure-docker/deploy-redis-store.sh
pure-docker/deploy-repo-updater.sh
pure-docker/deploy-searcher.sh
pure-docker/deploy-symbols.sh
pure-docker/deploy-syntect-server.sh
pure-docker/deploy-worker.sh
pure-docker/deploy-zoekt-indexserver.sh
pure-docker/deploy-zoekt-webserver.sh

This pull request is part of the Sourcegraph 5.1.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/49918)

release: sourcegraph@5.1.0

---

pure-docker/deploy-blobstore.sh
pure-docker/deploy-cadvisor.sh
pure-docker/deploy-codeinsights-db.sh
pure-docker/deploy-codeintel-db.sh
pure-docker/deploy-frontend-internal.sh
pure-docker/deploy-frontend.sh
pure-docker/deploy-github-proxy.sh
pure-docker/deploy-gitserver.sh
pure-docker/deploy-grafana.sh
pure-docker/deploy-migrator.sh
pure-docker/deploy-node-exporter.sh
pure-docker/deploy-otel-collector.sh
pure-docker/deploy-pgsql.sh
pure-docker/deploy-precise-code-intel-worker.sh
pure-docker/deploy-prometheus.sh
pure-docker/deploy-redis-cache.sh
pure-docker/deploy-redis-store.sh
pure-docker/deploy-repo-updater.sh
pure-docker/deploy-searcher.sh
pure-docker/deploy-symbols.sh
pure-docker/deploy-syntect-server.sh
pure-docker/deploy-worker.sh
pure-docker/deploy-zoekt-indexserver.sh
pure-docker/deploy-zoekt-webserver.sh

This pull request is part of the Sourcegraph 5.1.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/54459)

release: sourcegraph@5.1.1

---

pure-docker/deploy-blobstore.sh
pure-docker/deploy-cadvisor.sh
pure-docker/deploy-codeinsights-db.sh
pure-docker/deploy-codeintel-db.sh
pure-docker/deploy-frontend-internal.sh
pure-docker/deploy-frontend.sh
pure-docker/deploy-github-proxy.sh
pure-docker/deploy-gitserver.sh
pure-docker/deploy-grafana.sh
pure-docker/deploy-migrator.sh
pure-docker/deploy-node-exporter.sh
pure-docker/deploy-otel-collector.sh
pure-docker/deploy-pgsql.sh
pure-docker/deploy-precise-code-intel-worker.sh
pure-docker/deploy-prometheus.sh
pure-docker/deploy-redis-cache.sh
pure-docker/deploy-redis-store.sh
pure-docker/deploy-repo-updater.sh
pure-docker/deploy-searcher.sh
pure-docker/deploy-symbols.sh
pure-docker/deploy-syntect-server.sh
pure-docker/deploy-worker.sh
pure-docker/deploy-zoekt-indexserver.sh
pure-docker/deploy-zoekt-webserver.sh

This pull request is part of the Sourcegraph 5.1.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/54543)

release: sourcegraph@5.1.2

---

pure-docker/deploy-prometheus.sh

chore: delete left-over comment

---

pure-docker/deploy-blobstore.sh
pure-docker/deploy-cadvisor.sh
pure-docker/deploy-codeinsights-db.sh
pure-docker/deploy-codeintel-db.sh
pure-docker/deploy-frontend-internal.sh
pure-docker/deploy-frontend.sh
pure-docker/deploy-github-proxy.sh
pure-docker/deploy-gitserver.sh
pure-docker/deploy-grafana.sh
pure-docker/deploy-migrator.sh
pure-docker/deploy-node-exporter.sh
pure-docker/deploy-otel-collector.sh
pure-docker/deploy-pgsql.sh
pure-docker/deploy-precise-code-intel-worker.sh
pure-docker/deploy-prometheus.sh
pure-docker/deploy-redis-cache.sh
pure-docker/deploy-redis-store.sh
pure-docker/deploy-repo-updater.sh
pure-docker/deploy-searcher.sh
pure-docker/deploy-symbols.sh
pure-docker/deploy-syntect-server.sh
pure-docker/deploy-worker.sh
pure-docker/deploy-zoekt-indexserver.sh
pure-docker/deploy-zoekt-webserver.sh

This pull request is part of the Sourcegraph 5.1.3 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/54899)

release: sourcegraph@5.1.3

---

pure-docker/deploy-blobstore.sh
pure-docker/deploy-cadvisor.sh
pure-docker/deploy-codeinsights-db.sh
pure-docker/deploy-codeintel-db.sh
pure-docker/deploy-frontend-internal.sh
pure-docker/deploy-frontend.sh
pure-docker/deploy-github-proxy.sh
pure-docker/deploy-gitserver.sh
pure-docker/deploy-grafana.sh
pure-docker/deploy-migrator.sh
pure-docker/deploy-node-exporter.sh
pure-docker/deploy-otel-collector.sh
pure-docker/deploy-pgsql.sh
pure-docker/deploy-precise-code-intel-worker.sh
pure-docker/deploy-prometheus.sh
pure-docker/deploy-redis-cache.sh
pure-docker/deploy-redis-store.sh
pure-docker/deploy-repo-updater.sh
pure-docker/deploy-searcher.sh
pure-docker/deploy-symbols.sh
pure-docker/deploy-syntect-server.sh
pure-docker/deploy-worker.sh
pure-docker/deploy-zoekt-indexserver.sh
pure-docker/deploy-zoekt-webserver.sh

This pull request is part of the Sourcegraph 5.1.5 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.5)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/55328)

release: sourcegraph@5.1.5

---

pure-docker/deploy-blobstore.sh
pure-docker/deploy-cadvisor.sh
pure-docker/deploy-codeinsights-db.sh
pure-docker/deploy-codeintel-db.sh
pure-docker/deploy-frontend-internal.sh
pure-docker/deploy-frontend.sh
pure-docker/deploy-github-proxy.sh
pure-docker/deploy-gitserver.sh
pure-docker/deploy-grafana.sh
pure-docker/deploy-migrator.sh
pure-docker/deploy-node-exporter.sh
pure-docker/deploy-otel-collector.sh
pure-docker/deploy-pgsql.sh
pure-docker/deploy-precise-code-intel-worker.sh
pure-docker/deploy-prometheus.sh
pure-docker/deploy-redis-cache.sh
pure-docker/deploy-redis-store.sh
pure-docker/deploy-repo-updater.sh
pure-docker/deploy-searcher.sh
pure-docker/deploy-symbols.sh
pure-docker/deploy-syntect-server.sh
pure-docker/deploy-worker.sh
pure-docker/deploy-zoekt-indexserver.sh
pure-docker/deploy-zoekt-webserver.sh

This pull request is part of the Sourcegraph 5.1.7 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.7)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/56213)

release: sourcegraph@5.1.7

---

pure-docker/deploy-blobstore.sh
pure-docker/deploy-cadvisor.sh
pure-docker/deploy-codeinsights-db.sh
pure-docker/deploy-codeintel-db.sh
pure-docker/deploy-frontend-internal.sh
pure-docker/deploy-frontend.sh
pure-docker/deploy-github-proxy.sh
pure-docker/deploy-gitserver.sh
pure-docker/deploy-grafana.sh
pure-docker/deploy-migrator.sh
pure-docker/deploy-node-exporter.sh
pure-docker/deploy-otel-collector.sh
pure-docker/deploy-pgsql.sh
pure-docker/deploy-precise-code-intel-worker.sh
pure-docker/deploy-prometheus.sh
pure-docker/deploy-redis-cache.sh
pure-docker/deploy-redis-store.sh
pure-docker/deploy-repo-updater.sh
pure-docker/deploy-searcher.sh
pure-docker/deploy-symbols.sh
pure-docker/deploy-syntect-server.sh
pure-docker/deploy-worker.sh
pure-docker/deploy-zoekt-indexserver.sh
pure-docker/deploy-zoekt-webserver.sh

This pull request is part of the Sourcegraph 5.1.8 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.8)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/56395)

release: sourcegraph@5.1.8

---

pure-docker/deploy-blobstore.sh
pure-docker/deploy-cadvisor.sh
pure-docker/deploy-codeinsights-db.sh
pure-docker/deploy-codeintel-db.sh
pure-docker/deploy-frontend-internal.sh
pure-docker/deploy-frontend.sh
pure-docker/deploy-github-proxy.sh
pure-docker/deploy-gitserver.sh
pure-docker/deploy-grafana.sh
pure-docker/deploy-migrator.sh
pure-docker/deploy-node-exporter.sh
pure-docker/deploy-otel-collector.sh
pure-docker/deploy-pgsql.sh
pure-docker/deploy-precise-code-intel-worker.sh
pure-docker/deploy-prometheus.sh
pure-docker/deploy-redis-cache.sh
pure-docker/deploy-redis-store.sh
pure-docker/deploy-repo-updater.sh
pure-docker/deploy-searcher.sh
pure-docker/deploy-symbols.sh
pure-docker/deploy-syntect-server.sh
pure-docker/deploy-worker.sh
pure-docker/deploy-zoekt-indexserver.sh
pure-docker/deploy-zoekt-webserver.sh

Part of https://github.com/sourcegraph/sourcegraph/issues/56907
CI

release: sourcegraph@5.2.0

---

pure-docker/deploy-blobstore.sh
pure-docker/deploy-cadvisor.sh
pure-docker/deploy-codeinsights-db.sh
pure-docker/deploy-codeintel-db.sh
pure-docker/deploy-frontend-internal.sh
pure-docker/deploy-frontend.sh
pure-docker/deploy-github-proxy.sh
pure-docker/deploy-gitserver.sh
pure-docker/deploy-grafana.sh
pure-docker/deploy-migrator.sh
pure-docker/deploy-node-exporter.sh
pure-docker/deploy-otel-collector.sh
pure-docker/deploy-pgsql.sh
pure-docker/deploy-precise-code-intel-worker.sh
pure-docker/deploy-prometheus.sh
pure-docker/deploy-redis-cache.sh
pure-docker/deploy-redis-store.sh
pure-docker/deploy-repo-updater.sh
pure-docker/deploy-searcher.sh
pure-docker/deploy-symbols.sh
pure-docker/deploy-syntect-server.sh
pure-docker/deploy-worker.sh
pure-docker/deploy-zoekt-indexserver.sh
pure-docker/deploy-zoekt-webserver.sh

This pull request is part of the Sourcegraph 5.2.2 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/58049)

release: sourcegraph@5.2.2

---

pure-docker/deploy-blobstore.sh
pure-docker/deploy-cadvisor.sh
pure-docker/deploy-codeinsights-db.sh
pure-docker/deploy-codeintel-db.sh
pure-docker/deploy-frontend-internal.sh
pure-docker/deploy-frontend.sh
pure-docker/deploy-github-proxy.sh
pure-docker/deploy-gitserver.sh
pure-docker/deploy-grafana.sh
pure-docker/deploy-migrator.sh
pure-docker/deploy-node-exporter.sh
pure-docker/deploy-otel-collector.sh
pure-docker/deploy-pgsql.sh
pure-docker/deploy-precise-code-intel-worker.sh
pure-docker/deploy-prometheus.sh
pure-docker/deploy-redis-cache.sh
pure-docker/deploy-redis-store.sh
pure-docker/deploy-repo-updater.sh
pure-docker/deploy-searcher.sh
pure-docker/deploy-symbols.sh
pure-docker/deploy-syntect-server.sh
pure-docker/deploy-worker.sh
pure-docker/deploy-zoekt-indexserver.sh
pure-docker/deploy-zoekt-webserver.sh

This pull request is part of the Sourcegraph 5.2.3 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/58310)

release: sourcegraph@5.2.3

---

pure-docker/deploy-blobstore.sh
pure-docker/deploy-cadvisor.sh
pure-docker/deploy-codeinsights-db.sh
pure-docker/deploy-codeintel-db.sh
pure-docker/deploy-frontend-internal.sh
pure-docker/deploy-frontend.sh
pure-docker/deploy-github-proxy.sh
pure-docker/deploy-gitserver.sh
pure-docker/deploy-grafana.sh
pure-docker/deploy-migrator.sh
pure-docker/deploy-node-exporter.sh
pure-docker/deploy-otel-collector.sh
pure-docker/deploy-pgsql.sh
pure-docker/deploy-precise-code-intel-worker.sh
pure-docker/deploy-prometheus.sh
pure-docker/deploy-redis-cache.sh
pure-docker/deploy-redis-store.sh
pure-docker/deploy-repo-updater.sh
pure-docker/deploy-searcher.sh
pure-docker/deploy-symbols.sh
pure-docker/deploy-syntect-server.sh
pure-docker/deploy-worker.sh
pure-docker/deploy-zoekt-indexserver.sh
pure-docker/deploy-zoekt-webserver.sh

This pull request is part of the Sourcegraph 5.2.4 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.4)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/58662)

release: sourcegraph@5.2.4

---

pure-docker/deploy-blobstore.sh
pure-docker/deploy-cadvisor.sh
pure-docker/deploy-codeinsights-db.sh
pure-docker/deploy-codeintel-db.sh
pure-docker/deploy-frontend-internal.sh
pure-docker/deploy-frontend.sh
pure-docker/deploy-github-proxy.sh
pure-docker/deploy-gitserver.sh
pure-docker/deploy-grafana.sh
pure-docker/deploy-migrator.sh
pure-docker/deploy-node-exporter.sh
pure-docker/deploy-otel-collector.sh
pure-docker/deploy-pgsql.sh
pure-docker/deploy-precise-code-intel-worker.sh
pure-docker/deploy-prometheus.sh
pure-docker/deploy-redis-cache.sh
pure-docker/deploy-redis-store.sh
pure-docker/deploy-repo-updater.sh
pure-docker/deploy-searcher.sh
pure-docker/deploy-symbols.sh
pure-docker/deploy-syntect-server.sh
pure-docker/deploy-worker.sh
pure-docker/deploy-zoekt-indexserver.sh
pure-docker/deploy-zoekt-webserver.sh

This pull request is part of the Sourcegraph 5.2.5 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.5)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/58967)

release: sourcegraph@5.2.5

---

pure-docker/deploy-blobstore.sh
pure-docker/deploy-cadvisor.sh
pure-docker/deploy-codeinsights-db.sh
pure-docker/deploy-codeintel-db.sh
pure-docker/deploy-frontend-internal.sh
pure-docker/deploy-frontend.sh
pure-docker/deploy-github-proxy.sh
pure-docker/deploy-gitserver.sh
pure-docker/deploy-grafana.sh
pure-docker/deploy-migrator.sh
pure-docker/deploy-node-exporter.sh
pure-docker/deploy-otel-collector.sh
pure-docker/deploy-pgsql.sh
pure-docker/deploy-precise-code-intel-worker.sh
pure-docker/deploy-prometheus.sh
pure-docker/deploy-redis-cache.sh
pure-docker/deploy-redis-store.sh
pure-docker/deploy-repo-updater.sh
pure-docker/deploy-searcher.sh
pure-docker/deploy-symbols.sh
pure-docker/deploy-syntect-server.sh
pure-docker/deploy-worker.sh
pure-docker/deploy-zoekt-indexserver.sh
pure-docker/deploy-zoekt-webserver.sh

This pull request is part of the Sourcegraph 5.2.6 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.6)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/59481)

release: sourcegraph@5.2.6

---

pure-docker/deploy-blobstore.sh
pure-docker/deploy-cadvisor.sh
pure-docker/deploy-codeinsights-db.sh
pure-docker/deploy-codeintel-db.sh
pure-docker/deploy-frontend-internal.sh
pure-docker/deploy-frontend.sh
pure-docker/deploy-github-proxy.sh
pure-docker/deploy-gitserver.sh
pure-docker/deploy-grafana.sh
pure-docker/deploy-migrator.sh
pure-docker/deploy-node-exporter.sh
pure-docker/deploy-otel-collector.sh
pure-docker/deploy-pgsql.sh
pure-docker/deploy-precise-code-intel-worker.sh
pure-docker/deploy-prometheus.sh
pure-docker/deploy-redis-cache.sh
pure-docker/deploy-redis-store.sh
pure-docker/deploy-repo-updater.sh
pure-docker/deploy-searcher.sh
pure-docker/deploy-symbols.sh
pure-docker/deploy-syntect-server.sh
pure-docker/deploy-worker.sh
pure-docker/deploy-zoekt-indexserver.sh
pure-docker/deploy-zoekt-webserver.sh

This pull request is part of the Sourcegraph 5.2.7 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.7)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/59830)

release: sourcegraph@5.2.7

---

pure-docker/deploy-blobstore.sh
pure-docker/deploy-cadvisor.sh
pure-docker/deploy-codeinsights-db.sh
pure-docker/deploy-codeintel-db.sh
pure-docker/deploy-frontend-internal.sh
pure-docker/deploy-frontend.sh
pure-docker/deploy-gitserver.sh
pure-docker/deploy-grafana.sh
pure-docker/deploy-migrator.sh
pure-docker/deploy-node-exporter.sh
pure-docker/deploy-otel-collector.sh
pure-docker/deploy-pgsql.sh
pure-docker/deploy-precise-code-intel-worker.sh
pure-docker/deploy-prometheus.sh
pure-docker/deploy-redis-cache.sh
pure-docker/deploy-redis-store.sh
pure-docker/deploy-repo-updater.sh
pure-docker/deploy-searcher.sh
pure-docker/deploy-symbols.sh
pure-docker/deploy-syntect-server.sh
pure-docker/deploy-worker.sh
pure-docker/deploy-zoekt-indexserver.sh
pure-docker/deploy-zoekt-webserver.sh

This pull request is part of the Sourcegraph 5.3.0 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.3.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/60032)

release: sourcegraph@5.3.0

---

pure-docker/deploy-blobstore.sh
pure-docker/deploy-cadvisor.sh
pure-docker/deploy-codeinsights-db.sh
pure-docker/deploy-codeintel-db.sh
pure-docker/deploy-frontend-internal.sh
pure-docker/deploy-frontend.sh
pure-docker/deploy-gitserver.sh
pure-docker/deploy-grafana.sh
pure-docker/deploy-migrator.sh
pure-docker/deploy-node-exporter.sh
pure-docker/deploy-otel-collector.sh
pure-docker/deploy-pgsql.sh
pure-docker/deploy-precise-code-intel-worker.sh
pure-docker/deploy-prometheus.sh
pure-docker/deploy-redis-cache.sh
pure-docker/deploy-redis-store.sh
pure-docker/deploy-repo-updater.sh
pure-docker/deploy-searcher.sh
pure-docker/deploy-symbols.sh
pure-docker/deploy-syntect-server.sh
pure-docker/deploy-worker.sh
pure-docker/deploy-zoekt-indexserver.sh
pure-docker/deploy-zoekt-webserver.sh

This pull request is part of the Sourcegraph 5.3.1 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.3.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/60691)

release: sourcegraph@5.3.1

---

pure-docker/deploy-blobstore.sh
pure-docker/deploy-cadvisor.sh
pure-docker/deploy-codeinsights-db.sh
pure-docker/deploy-codeintel-db.sh
pure-docker/deploy-frontend-internal.sh
pure-docker/deploy-frontend.sh
pure-docker/deploy-gitserver.sh
pure-docker/deploy-grafana.sh
pure-docker/deploy-migrator.sh
pure-docker/deploy-node-exporter.sh
pure-docker/deploy-otel-collector.sh
pure-docker/deploy-pgsql.sh
pure-docker/deploy-precise-code-intel-worker.sh
pure-docker/deploy-prometheus.sh
pure-docker/deploy-redis-cache.sh
pure-docker/deploy-redis-store.sh
pure-docker/deploy-repo-updater.sh
pure-docker/deploy-searcher.sh
pure-docker/deploy-symbols.sh
pure-docker/deploy-syntect-server.sh
pure-docker/deploy-worker.sh
pure-docker/deploy-zoekt-indexserver.sh
pure-docker/deploy-zoekt-webserver.sh

This pull request is part of the Sourcegraph 5.3.2 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.3.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/60972)

release: sourcegraph@5.3.2

---

pure-docker/deploy-blobstore.sh
pure-docker/deploy-cadvisor.sh
pure-docker/deploy-codeinsights-db.sh
pure-docker/deploy-codeintel-db.sh
pure-docker/deploy-frontend-internal.sh
pure-docker/deploy-frontend.sh
pure-docker/deploy-gitserver.sh
pure-docker/deploy-grafana.sh
pure-docker/deploy-migrator.sh
pure-docker/deploy-node-exporter.sh
pure-docker/deploy-otel-collector.sh
pure-docker/deploy-pgsql.sh
pure-docker/deploy-precise-code-intel-worker.sh
pure-docker/deploy-prometheus.sh
pure-docker/deploy-redis-cache.sh
pure-docker/deploy-redis-store.sh
pure-docker/deploy-repo-updater.sh
pure-docker/deploy-searcher.sh
pure-docker/deploy-symbols.sh
pure-docker/deploy-syntect-server.sh
pure-docker/deploy-worker.sh
pure-docker/deploy-zoekt-indexserver.sh
pure-docker/deploy-zoekt-webserver.sh

This pull request is part of the Sourcegraph 5.3.3 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.3.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/61302)

release: sourcegraph@5.3.3
